### ISSUE TITLE
Crash when selecting aethon encounter

### ISSUE THREAD

**Issue by progenitor-amborella** [PyrexPi/prophet#3]
```
Do you want to keep your preferred device (delete device.txt to reset preferences) y/n: n
Choose your encounter file (templar/aethon): aethon
Traceback (most recent call last):
	File "main.pay", line 46, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Desktop\prophet\\aethon.json'
[15420] Failed to execute script main
```

However... aethon.json is in the directory, and templar runs fine, so I'm not sure what causes it. Does not change if device is kept or not.

**Comment by PyrexPi** [comment]
I don't know how it shows "aetheon" instead of "atheon", but I think that's the problem. Maybe it's a spelling mistake? Make sure that the name that you are inputting matches the name of the file on that directory (it's best if you don't change the name of the files). If you have further problems report back and I'll take a closer look at it.

**Comment by progenitor-amborella** [comment]
I typed this in manually as the program closes so fast that I was reading off a screenshot. I do believe I was mistyping atheon, and this should've occurred to me with the error message even thought it was late at night.

Feel free to close this issue, sorry!
